#!/usr/bin/env python
#
# Copyright (c) 2013, Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import atexit
import json
import os
import re
import subprocess
import sys
import tempfile

import jinja2

inventory_template = jinja2.Environment(trim_blocks=True, lstrip_blocks=True).from_string("""
[all]
{% for machine_num, machine in status.machines.iteritems() %}
{{ machine['dns-name'] }}
{% endfor %}

{% for service_name, service in status.services.iteritems() %}
[{{ service_name }}]
{% for unit_name, unit in service.units.iteritems() %}
{% if unit.machine %}
{{ status.machines[unit.machine]['dns-name'] }}
{% endif %}
{% endfor %}

{% endfor %}
""")


def is_exe(fpath):
	"""Test if fpath is an executable file."""
	return os.path.isfile(fpath) and os.access(fpath, os.X_OK)


def which(program):
	"""Get the absolute path to the executable by name,
	if it exists in the $PATH."""
	fpath, fname = os.path.split(program)
	if fpath:
		if is_exe(program):
			return program
	else:
		for path in os.environ["PATH"].split(os.pathsep):
			path = path.strip('"')
			exe_file = os.path.join(path, program)
			if is_exe(exe_file):
				return exe_file

	return None


class JujuCmdError(Exception):
	"""Juju command failure exception."""
	def __init__(self, messsage, stderr=None, rc=-1):
		self.stderr = stderr
		self.rc = rc
		Exception.__init__(self, message)


def juju_status():
	"""Deserialize the current Juju status."""
	p = subprocess.Popen(["juju", "status", "--format", "json"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	stdout, stderr = p.communicate()
	if p.returncode:
		raise JujuCmdError("Error executing 'juju status'. Please check your Juju environment and try again.",
			stderr=stderr, rc=p.returncode)
	return json.loads(stdout)


def to_inventory_file(status):
	return inventory_template.render(status=status)


if __name__ == '__main__':
	try:
		# Check that juju is installed
		juju_cmd_path = which("juju")
		if not juju_cmd_path:
			raise Exception("""'juju' was not found in your path, check your Juju installation.
See https://juju.ubuntu.com/install/ for installation instructions.""")

		# Build an Ansible inventory file from Juju environment status
		status = juju_status()
		inventory = to_inventory_file(status)

		# For --show, don't need to run ansible
		if sys.argv[1:] and sys.argv[1:][0] == '--show':
			print inventory
			os._exit(0)

		# Derive ansible command, check that it is actually installed
		ansible_cmd = re.sub('juju-', '', os.path.basename(sys.argv[0]))
		ansible_cmd_path = which(ansible_cmd)
		if not ansible_cmd_path:
			raise Exception("""'%s' was not found in your path, check your Ansible installation.
See http://www.ansibleworks.com/docs/intro_installation.html for installation instructions.""" % (
				ansible_cmd))

		# Write inventory file to temp file, cleanup at exit
		inventory_filename = None
		with tempfile.NamedTemporaryFile(delete=False) as f:
			f.write(inventory)
			inventory_filename = f.name

		def cleanup(*args, **kwargs):
			os.unlink(inventory_filename)
		atexit.register(cleanup)

		# Build ansible command line and execute it
		cmdline = [ansible_cmd, "-i", inventory_filename]
		cmdline.extend(sys.argv[1:])
		p = subprocess.Popen(cmdline)
		p.wait()
		os._exit(p.returncode)
	except Exception, e:
		print >>sys.stderr, "Error: %s" % (e.message)
		os._exit(1)
	except:
		print >>sys.stderr, "An unknown error occurred."
		os._exit(1)
